# -*- coding: utf-8 -*-
"""boltz2_proto_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/MarcAmil30/DOGMA/blob/main/boltz2_proto_test.ipynb
"""



!pip install git+https://github.com/evo-design/proto-tools.git

import pandas as pd
import numpy as np
import requests

from pathlib import Path

from proto_tools import (
    Mmseqs2HomologySearchConfig,
    Boltz2Config,
    Boltz2Input,
    Chain,
    Complex,
    run_boltz2,
)

fn="https://raw.githubusercontent.com/MarcAmil30/DOGMA/refs/heads/main/smxArJipt0KSbaYk.txt"

def get_full_seq(transcript):
    transcript = transcript.split(".")[0]   # drop version if present
    url = f"https://rest.ensembl.org/sequence/id/{transcript}"
    r = requests.get(url, params={"type": "protein"},
                     headers={"Content-Type": "application/json"})
    r.raise_for_status()
    return r.json()["seq"]

def get_protein_info(fn, i):
    """
    Get the protein sequence before & after the mutation.
    Handles single-residue and multi-residue (block) changes.
    input:
        fn: file name (VEP tab-delimited output)
        i:  the row index clicked by the user
    output:
        protein_before: protein sequence before the mutation
        protein_after:  protein sequence after the mutation
    """
    df = pd.read_csv(fn, sep="\t")
    aa = df.loc[i, "Amino_acids"]

    # bail out if this row has no amino-acid change
    if not isinstance(aa, str) or "/" not in aa:
        return "", ""

    aa_ref, aa_alt = aa.split("/")
    ref_block = "" if aa_ref == "-" else aa_ref      # "-" means empty (indel)
    alt_block = "" if aa_alt == "-" else aa_alt

    # Protein_position is "711" (single) or "1787-1788" (range), 1-based inclusive
    parts = str(df.loc[i, "Protein_position"]).split("-")
    start = int(parts[0])
    end   = int(parts[-1])          # equals start when it's a single position

    transcript = df.loc[i, "Feature"]
    full_seq = get_full_seq(transcript)

    idx0 = start - 1                # 0-based start
    observed = full_seq[idx0:end]  # the residues the table refers to
    assert observed == ref_block, (
        f"reference mismatch: sequence has {observed!r}, table says {ref_block!r}"
    )

    protein_before = full_seq
    protein_after  = full_seq[:idx0] + alt_block + full_seq[end:]
    return protein_before, protein_after

tseq_wt,tseq_mut=get_protein_info(fn, 0)

len(tseq_wt),len(tseq_mut)

missense

def predict_protein_struc (seq):
  chain = Chain(sequence=seq, id="A",entity_type="protein")
  complex = Complex(chains=[chain])
  inputs = Boltz2Input(complexes=[complex])

  # Configure Boltz-2 with reduced settings for a fast demonstration run
  config = Boltz2Config(
      verbose=False,
      device="cuda",  # Change to "cpu" if no GPU available
      use_msa=True,
      msa_search_config=Mmseqs2HomologySearchConfig(search_mode="remote"),
      recycling_steps=3,
      diffusion_samples=1,
  )

  result=run_boltz2(inputs, config)
  return result

t_result=predict_protein_struc (tseq_wt)

t_result.structures[0].metrics

# save metrics
import pickle

with open("result_0_wt.pkl", "wb") as f:
  pickle.dump(t_result, f)

import py3Dmol

def get_structure_text(structure):
    """Return (text, fmt) for a proto_tools structure, trying common export methods."""
    for meth, fmt in [("to_pdb", "pdb"), ("to_cif", "cif"),
                      ("to_mmcif", "cif"), ("pdb_string", "pdb"), ("cif_string", "cif")]:
        obj = getattr(structure, meth, None)
        if obj is None:
            continue
        return (obj() if callable(obj) else obj), fmt
    # fallback: write to disk then read back
    for meth, fmt in [("write_pdb", "pdb"), ("save_pdb", "pdb"), ("write_cif", "cif")]:
        if hasattr(structure, meth):
            path = f"/tmp/pred.{fmt}"
            getattr(structure, meth)(path)
            return open(path).read(), fmt
    raise RuntimeError("Couldn't export structure — check dir(structure) for the right method.")


def visualize_with_mutation(structure, highlight_resi, chain="A", width=800, height=600):
    """
    Cartoon colored by B-factor (pLDDT), with the mutated residue(s) highlighted.
    highlight_resi: int or list of ints (1-based residue numbers), e.g. 711 or [1787, 1788]
    """
    if isinstance(highlight_resi, int):
        highlight_resi = [highlight_resi]

    text, fmt = get_structure_text(structure)
    sel = {"chain": chain, "resi": highlight_resi}

    view = py3Dmol.view(width=width, height=height)
    view.addModel(text, fmt)

    # base: cartoon colored by pLDDT (stored in B-factor), 0-100 low->high
    view.setStyle({}, {"cartoon": {
        "colorscheme": {"prop": "b", "gradient": "roygb", "min": 0, "max": 100}
    }})

    # highlight the mutated residue(s)
    view.addStyle(sel, {"stick":  {"colorscheme": "magentaCarbon", "radius": 0.3}})
    view.addStyle(sel, {"sphere": {"colorscheme": "magentaCarbon", "opacity": 0.5}})
    view.addResLabels(sel, {"fontSize": 12, "backgroundOpacity": 0.7})

    view.zoomTo()
    return view.show()


# usage — the mutated position is the Protein_position you parsed earlier
visualize_with_mutation(t_result.structures[0], 711)          # single residue
# visualize_with_mutation(t_result.structures[0], [1787, 1788])  # block mutation

df.loc[0,"Protein_position"]

def save_structure(structure, path):
    """Save a proto_tools structure to disk. Format is inferred from the file extension."""
    text, fmt = get_structure_text(structure)
    # if you asked for .pdb but the library only gave .cif (or vice versa), warn
    ext = path.rsplit(".", 1)[-1].lower()
    if ext not in (fmt, "cif" if fmt == "cif" else "pdb"):
        print(f"note: structure exported as {fmt}, but you named the file .{ext}")
    with open(path, "w") as f:
        f.write(text)
    print(f"saved -> {path}")

save_structure(t_result.structures[0], "brca1_wt.cif")

t_result_mut=predict_protein_struc (tseq_mut)

t_result_mut.structures[0].metrics

t_result.structures[0].metrics

visualize_with_mutation(t_result_mut.structures[0], 711)

with open("result_0_mut.pkl","wb") as f:
  pickle.dump(t_result_mut, f)

save_structure(t_result_mut.structures[0], "brca1_mut.cif")

def demo_visualize(seq_pkl_fn,mut_pkl_fn):
  with open(seq_pkl_fn,"rb") as f:
    seq_result=pickle.load(f)
  with open(mut_pkl_fn,"rb") as f:
    mut_result=pickle.load(f)

  visualize_with_mutation(seq_result.structures[0], 711)
  visualize_with_mutation(mut_result.structures[0], 711)

  print(f" Confidence score wt:  {seq_result.structures[0].metrics.confidence_score:.6f}")
  print(f" Confidence score mut: {mut_result.structures[0].metrics.confidence_score:.6f}")
  print(f" Confidence score diff: {mut_result.structures[0].metrics.confidence_score-seq_result.structures[0].metrics.confidence_score:.6f}")

demo_visualize("result_0_mut.pkl","result_0_wt.pkl")

