# -*- coding: utf-8 -*-
"""esm2_proto_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqulasvn16boVVw8xFkdzkD8zSZUV6XS
"""

!pip install git+https://github.com/evo-design/proto-tools.git

import pandas as pd
import numpy as np
import requests

def get_full_seq(transcript):
    transcript = transcript.split(".")[0]   # drop version if present
    url = f"https://rest.ensembl.org/sequence/id/{transcript}"
    r = requests.get(url, params={"type": "protein"},
                     headers={"Content-Type": "application/json"})
    r.raise_for_status()
    return r.json()["seq"]

def get_protein_info(fn, i):
    """
    Get the protein sequence before & after the mutation.
    Handles single-residue and multi-residue (block) changes.
    input:
        fn: file name (VEP tab-delimited output)
        i:  the row index clicked by the user
    output:
        protein_before: protein sequence before the mutation
        protein_after:  protein sequence after the mutation
    """
    df = pd.read_csv(fn, sep="\t")
    aa = df.loc[i, "Amino_acids"]

    # bail out if this row has no amino-acid change
    if not isinstance(aa, str) or "/" not in aa:
        return "", ""

    aa_ref, aa_alt = aa.split("/")
    ref_block = "" if aa_ref == "-" else aa_ref      # "-" means empty (indel)
    alt_block = "" if aa_alt == "-" else aa_alt

    # Protein_position is "711" (single) or "1787-1788" (range), 1-based inclusive
    parts = str(df.loc[i, "Protein_position"]).split("-")
    start = int(parts[0])
    end   = int(parts[-1])          # equals start when it's a single position

    transcript = df.loc[i, "Feature"]
    full_seq = get_full_seq(transcript)

    idx0 = start - 1                # 0-based start
    observed = full_seq[idx0:end]  # the residues the table refers to
    assert observed == ref_block, (
        f"reference mismatch: sequence has {observed!r}, table says {ref_block!r}"
    )

    protein_before = full_seq
    protein_after  = full_seq[:idx0] + alt_block + full_seq[end:]
    return protein_before, protein_after

fn="https://raw.githubusercontent.com/MarcAmil30/DOGMA/refs/heads/main/smxArJipt0KSbaYk.txt"

tseq_wt,tseq_mut=get_protein_info(fn, 0)

tseq_mut

from proto_tools import (
    ESM2ScoringConfig,
    ESM2ScoringInput,
    run_esm2_score,
)

def score_variants (wt,mut):
  inputs = ESM2ScoringInput(sequences=[wt, mut])
  config = ESM2ScoringConfig(
      batch_size=5,
      return_logits=False,
      device="cuda",  # Change to "cpu" if no GPU available
  )
  score_result = run_esm2_score(inputs, config)

  return score_result

  return score_result['perplexity']

result=score_variants(tseq_wt,tseq_mut)

result.scores[0].perplexity

def print_perplexcity_change (result):
  wt=result.scores[0].perplexity
  mut=result.scores[0].perplexity
  print (f"perplexity WT: {wt:.5f}")
  print (f"perplexity MUT: {mut:.5f}")
  print (f"perplexity diff: {mut:.5f}")

print_perplexcity_change (result)

